services:
  postgresql:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-volumes:/var/lib/postgresql/data
    restart: always
    networks:
      - chula-network
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3200:3000"
    restart: always
    networks:
      - chula-network
  be:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9899:9898"
    restart: always
    depends_on:
      - postgresql
    networks:
      - chula-network

volumes:
  pg-volumes:

networks:
  chula-network:
